### ISSUE TITLE
Characters' descriptions are sometimes missing-erased. Might related to ppl who copy pasted desc or with Personas?

### ISSUE THREAD

**Issue by Aschent89** [Aschent89/tdn-bug-tracking#102]
**Date Submitted:** 05/17/2024<br>**Time Submitted:** 08:27:52<br>**Race:** HalfElf<br>**Class 1:** Rogue **Level:** 1<br>**Class 2:** Fighter **Level:** 1<br>**Class 3:** N/A **Level:** 0<br><br>**Bug Description:** [Characters' descriptions are sometimes missing-erased. Might related to ppl who copy pasted desc or with Personas?]<br>**Area Name:** ((OOC Area)) Welcome to The Dragon's Neck!<br>**Area Tag:** brc_ooc<br>**Location:** #AREA#brc_ooc#POSITION_X#     109.050003052#POSITION_Y#      43.700000763#POSITION_Z#       0.000000000#ORIENTATION#     286.800018311#END#

**Comment by KT28dev** [comment]
Repeat: https://github.com/Aschent89/tdn-bug-tracking/issues/103
