### ISSUE TITLE
Personas & Portrait changes

### ISSUE THREAD

**Issue by Aschent89** [Aschent89/tdn-bug-tracking#311]
Reports of no way to change portraits, might be a player-training issue.

**UPDATE**: This seems to be for default persona only.

**Comment by Aschent89** [comment]
> !portrait option was moved to !personas yet personas dialogue does not have an option for portrait setup. Thank you.
Area Name
The Wealdath: Circle of the Elements
Area Tag
dan_ytelext
Location
#AREA#dan_ytelext#POSITION_X# 134.075393677#POSITION_Y# 47.316074371#POSITION_Z# -0.023783397#ORIENTATION# 142.799987793#END#

**Comment by KT28dev** [comment]
This is intended, default portrait can only be changed by help with a DM (it's controlled with the same variable for all other face/skintone color changes)
