### ISSUE TITLE
DMs can't understand PC languages.

### ISSUE THREAD

**Issue by Aschent89** [Aschent89/tdn-bug-tracking#41]
**Date Submitted:** 04/17/2024<br>**Time Submitted:** 10:39:41<br>**Race:** SunElf<br>**Class 1:** Fighter **Level:** 1<br>**Class 2:** N/A **Level:** 0<br>**Class 3:** N/A **Level:** 0<br><br>**Bug Description:** [DMs can't understand PC languages.]<br>**Area Name:** Murann: Tethir Thoroughfare<br>**Area Tag:** dan_mrn_thrrthfr<br>**Location:** #AREA#dan_mrn_thrrthfr#POSITION_X#     163.842742920#POSITION_Y#     106.052017212#POSITION_Z#       5.000000000#ORIENTATION#     180.000000000#END#

**Comment by KT28dev** [comment]
This should be fixed now as of https://github.com/Aschent89/The-Dragons-Neck/pull/4838
