### ISSUE TITLE
I think I'm hitting way too hard with non-critcal hits, think something is broken with warslinger

### ISSUE THREAD

**Issue by Aschent89** [Aschent89/tdn-bug-tracking#469]
**Date Submitted:** 06/04/2024<br>**Time Submitted:** 02:10:26<br>**Race:** StrongheartHalfling<br>**Class 1:** Ranger **Level:** 3<br>**Class 2:** Warsling Sniper **Level:** 1<br>**Class 3:** N/A **Level:** 0<br><br>**Bug Description:** [I think I'm hitting way too hard with non-critcal hits, think something is broken with warslinger]<br>**Area Name:** Fool's Canyon: Mine<br>**Area Tag:** asc_onapprchtrdcave<br>**Location:** #AREA#asc_onapprchtrdcave#POSITION_X#      95.332588196#POSITION_Y#      75.447776794#POSITION_Z#       0.000000000#ORIENTATION#      17.257905960#END#

**Comment by Aschent89** [comment]
> To clarify about the warslinger damage, I'm hitting way higher than my stat sheet numbers

**Comment by Aschent89** [comment]
> Sorry for the third follow up bug report, but I crit for 57 on a goblin with a 1d4+1d4 x2 sling, so something is def broken with the damage bonus of the sling from Warslinger.

**Comment by Aschent89** [comment]
> Fourth report, damage seemed to return to normal and I'm no longer hitting very high

**Comment by kevincbryan** [comment]
I wasn't getting any unusual crits, until I drank a potion of bull's strength, after which I immediately got a crit for 17.
Strength shouldn't apply to base sling damage to my knowledge.

Damage should have been (2d4)x2 at most for 16.

**Comment by kevincbryan** [comment]
Hmm, I think based on this and #398 there may be something going on with the temporary damage bonus abilities, perhaps interacting oddly with Sniper Vision cpecifically. When using the level 3 version of Wild Path - Wild Shot, I was able to hit 9 damage vs a non-favored enemy dog. Which, while not as large a number as we mention here, is higher than it should be (2d4 max of 8).

**Comment by kevincbryan** [comment]
I'm also never rolling a 2 on damage, which should be possible on a 2d4.
