### ISSUE TITLE
the DM eaveasdrop command should probably on by default.

### ISSUE THREAD

**Issue by Aschent89** [Aschent89/tdn-bug-tracking#494]
**Date Submitted:** 06/06/2024<br>**Time Submitted:** 07:17:19<br>**Race:** WildElf<br>**Class 1:** Fighter **Level:** 1<br>**Class 2:** N/A **Level:** 0<br>**Class 3:** N/A **Level:** 0<br><br>**Bug Description:** [the DM eaveasdrop command should probably on by default.]<br>**Area Name:** Tethir Road: Murann Outskirts<br>**Area Tag:** Ca_Mrn_Outskirts<br>**Location:** #AREA#Ca_Mrn_Outskirts#POSITION_X#     103.017227173#POSITION_Y#      45.992389679#POSITION_Z#       4.821607113#ORIENTATION#     175.500000000#END#

**Comment by KT28dev** [comment]
This is already the case.
