### ISSUE TITLE
Description changes don't persist between log-outs

### ISSUE THREAD

**Issue by Aschent89** [Aschent89/tdn-bug-tracking#87]
**Date Submitted:** 05/13/2024<br>**Time Submitted:** 03:29:37<br>**Race:** Human<br>**Class 1:** Favored Soul **Level:** 2<br>**Class 2:** N/A **Level:** 0<br>**Class 3:** N/A **Level:** 0<br><br>**Bug Description:** [Description changes don't persist between log-outs]<br>**Area Name:** ((OOC Area)) Welcome to The Dragon's Neck!<br>**Area Tag:** brc_ooc<br>**Location:** #AREA#brc_ooc#POSITION_X#      21.463636398#POSITION_Y#     100.157592773#POSITION_Z#       0.000000000#ORIENTATION#      45.508262634#END#

**Comment by KT28dev** [comment]
Repeat: https://github.com/Aschent89/tdn-bug-tracking/issues/103
