### ISSUE TITLE
Don't know what's causing it, but sometimes the !tailor menu just randomly opens for me. Either when I'm sitting still or running around!

### ISSUE THREAD

**Issue by Aschent89** [Aschent89/tdn-bug-tracking#89]
**Date Submitted:** 05/13/2024<br>**Time Submitted:** 11:26:45<br>**Race:** Human<br>**Class 1:** Rogue **Level:** 2<br>**Class 2:** N/A **Level:** 0<br>**Class 3:** N/A **Level:** 0<br><br>**Bug Description:** [Don't know what's causing it, but sometimes the !tailor menu just randomly opens for me. Either when I'm sitting still or running around!]<br>**Area Name:** ((OOC Area)) Welcome to The Dragon's Neck!<br>**Area Tag:** brc_ooc<br>**Location:** #AREA#brc_ooc#POSITION_X#      89.966033936#POSITION_Y#      52.895385742#POSITION_Z#       0.000000000#ORIENTATION#     263.899993896#END#

**Comment by Aschent89** [comment]
Experimental Fix going live with: `9b84912b`

**Comment by KT28dev** [comment]
Should be fixed by: https://github.com/Aschent89/The-Dragons-Neck/pull/4842
